CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'EDITOR');
CREATE TYPE "PublicationStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "ContentLocale" AS ENUM ('PT_BR', 'EN_US');

CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL DEFAULT 'EDITOR', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Article" ("id" TEXT NOT NULL, "authorId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Article_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ArticleTranslation" ("id" TEXT NOT NULL, "articleId" TEXT NOT NULL, "locale" "ContentLocale" NOT NULL, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "excerpt" TEXT, "contentHtml" TEXT NOT NULL DEFAULT '', "draftTitle" TEXT, "draftExcerpt" TEXT, "draftContentHtml" TEXT, "hasUnpublishedChanges" BOOLEAN NOT NULL DEFAULT false, "status" "PublicationStatus" NOT NULL DEFAULT 'DRAFT', "coverImageId" TEXT, "ogImageId" TEXT, "publishedAt" TIMESTAMP(3), "seoTitle" TEXT, "seoDescription" TEXT, "canonicalUrl" TEXT, "readingTimeMinutes" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ArticleTranslation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CategoryTranslation" ("id" TEXT NOT NULL, "categoryId" TEXT NOT NULL, "locale" "ContentLocale" NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT, CONSTRAINT "CategoryTranslation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Tag" ("id" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Tag_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TagTranslation" ("id" TEXT NOT NULL, "tagId" TEXT NOT NULL, "locale" "ContentLocale" NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, CONSTRAINT "TagTranslation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MediaAsset" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "provider" TEXT NOT NULL, "filename" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" INTEGER NOT NULL, "width" INTEGER, "height" INTEGER, "altText" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MediaAsset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "_ArticleCategory" ("A" TEXT NOT NULL, "B" TEXT NOT NULL);
CREATE TABLE "_ArticleTag" ("A" TEXT NOT NULL, "B" TEXT NOT NULL);

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE INDEX "ArticleTranslation_locale_status_publishedAt_idx" ON "ArticleTranslation"("locale", "status", "publishedAt");
CREATE UNIQUE INDEX "ArticleTranslation_articleId_locale_key" ON "ArticleTranslation"("articleId", "locale");
CREATE UNIQUE INDEX "ArticleTranslation_locale_slug_key" ON "ArticleTranslation"("locale", "slug");
CREATE UNIQUE INDEX "CategoryTranslation_categoryId_locale_key" ON "CategoryTranslation"("categoryId", "locale");
CREATE UNIQUE INDEX "CategoryTranslation_locale_slug_key" ON "CategoryTranslation"("locale", "slug");
CREATE UNIQUE INDEX "TagTranslation_tagId_locale_key" ON "TagTranslation"("tagId", "locale");
CREATE UNIQUE INDEX "TagTranslation_locale_slug_key" ON "TagTranslation"("locale", "slug");
CREATE UNIQUE INDEX "MediaAsset_key_key" ON "MediaAsset"("key");
CREATE UNIQUE INDEX "_ArticleCategory_AB_unique" ON "_ArticleCategory"("A", "B");
CREATE INDEX "_ArticleCategory_B_index" ON "_ArticleCategory"("B");
CREATE UNIQUE INDEX "_ArticleTag_AB_unique" ON "_ArticleTag"("A", "B");
CREATE INDEX "_ArticleTag_B_index" ON "_ArticleTag"("B");

ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Article" ADD CONSTRAINT "Article_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ArticleTranslation" ADD CONSTRAINT "ArticleTranslation_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ArticleTranslation" ADD CONSTRAINT "ArticleTranslation_coverImageId_fkey" FOREIGN KEY ("coverImageId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ArticleTranslation" ADD CONSTRAINT "ArticleTranslation_ogImageId_fkey" FOREIGN KEY ("ogImageId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CategoryTranslation" ADD CONSTRAINT "CategoryTranslation_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TagTranslation" ADD CONSTRAINT "TagTranslation_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_ArticleCategory" ADD CONSTRAINT "_ArticleCategory_A_fkey" FOREIGN KEY ("A") REFERENCES "ArticleTranslation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_ArticleCategory" ADD CONSTRAINT "_ArticleCategory_B_fkey" FOREIGN KEY ("B") REFERENCES "CategoryTranslation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_ArticleTag" ADD CONSTRAINT "_ArticleTag_A_fkey" FOREIGN KEY ("A") REFERENCES "ArticleTranslation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_ArticleTag" ADD CONSTRAINT "_ArticleTag_B_fkey" FOREIGN KEY ("B") REFERENCES "TagTranslation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
